---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
spec:
  params:
  - name: buildRevision
    description: The revision of the build, i.e. the commit revision of the application repository
  - name: appGitUrl
    description: The application repository
  - name: configGitUrl
    description: The application config (GitOps) repository
  - name: appImage
    description: The application Docker image name
  workspaces:
  - name: app-source
  - name: config-source

  tasks:
  - name: build-app
    taskRef:
      name: build-app
    params:
    - name: buildRevision
      value: $(params.buildRevision)
    - name: appGitUrl
      value: $(params.appGitUrl)
    - name: appImage
      value: $(params.appImage)
    workspaces:
    - name: app-source
      workspace: app-source

  - name: deploy-staging
    taskRef:
      name: deploy
    runAfter:
    - build-app
    params:
    - name: environment
      value: staging
    - name: argo-app-name
      value: app-staging
    - name: configGitUrl
      value: $(params.configGitUrl)
    - name: appImage
      value: $(params.appImage)
    - name: buildRevision
      value: $(params.buildRevision)
    workspaces:
    - name: config-source
      workspace: config-source

  - name: deploy-prod
    taskRef:
      name: deploy
    runAfter:
    - deploy-staging
    params:
    - name: environment
      value: production
    - name: argo-app-name
      value: app-prod
    - name: configGitUrl
      value: $(params.configGitUrl)
    - name: appImage
      value: $(params.appImage)
    - name: buildRevision
      value: $(params.buildRevision)
    workspaces:
    - name: config-source
      workspace: config-source
