apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-staging
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: staging
    repoURL: https://github.com/ar4mirez/weatherapp-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
