apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weatherapp-prod
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: production
    repoURL: https://github.com/ar4mirez/weatherapp-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true